name: CD

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sales-forecast-backend:latest
      
      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sales-forecast-frontend:latest
      
      # Déploiement via SSH vers un serveur cloud
      - name: Deploy to Cloud Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Créer un répertoire pour le déploiement si nécessaire
            mkdir -p ~/sales-forecast-app
            
            # Aller dans le répertoire de déploiement
            cd ~/sales-forecast-app
            
            # Télécharger le fichier docker-compose.yml depuis le dépôt
            curl -o docker-compose.yml https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yml
            
            # Mettre à jour les images Docker
            docker-compose pull
            
            # Redémarrer les services
            docker-compose down
            docker-compose up -d
            
            # Vérifier que les services sont en cours d'exécution
            docker-compose ps