name: CD

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend/Dockerfile            # <-- case-sensitive: must match your repo
          push: true
          platforms: linux/amd64,linux/arm64   # optional — remove if you don't need multi-arch
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sales-forecast-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/sales-forecast-backend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/sales-forecast-backend:cache
          cache-to: type=registry,mode=max,ref=${{ secrets.DOCKERHUB_USERNAME }}/sales-forecast-backend:cache

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile           # <-- check file name and case here
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sales-forecast-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/sales-forecast-frontend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/sales-forecast-frontend:cache
          cache-to: type=registry,mode=max,ref=${{ secrets.DOCKERHUB_USERNAME }}/sales-forecast-frontend:cache
