name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub (optional)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and start Docker Compose
      - name: Build and run Docker Compose
        run: |
          docker compose -f docker-compose.yml up --build -d

      # Step 4: Run tests (optional)
      #- name: Run frontend tests
      #  run: |
      #    docker compose exec sampleproject npm test

      # Step 5: Stop services after job
      - name: Stop Docker Compose
        if: always()
        run: docker compose down
